[build]
  command = "npm install --no-optional && npm rebuild && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--no-optional"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin" 